# brew tap-new uses this file to generate an autobump workflow for the new tap
name: brew bump

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Every Sunday at midnight.
    - cron: '0 0 * * 0'

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  autobump:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@e99025eb970cfa124b8284a35463d87426917478 # 2026.09.28.1

      - name: Set up git
        id: git_setup
        uses: Homebrew/actions/git-user-config@e99025eb970cfa124b8284a35463d87426917478 # 2026.09.28.1

      - name: Bump formulae and casks
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          TAP_NAME: ${{ steps.set-up-homebrew.outputs.tap-name }}
        run: brew bump --tap="$TAP_NAME" --full-name --open-pr --no-fork --bump-synced
